In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('data/fuzzy_test_class_only.csv', index_col=[0])
#df.reset_index(drop=True, inplace=True)
df.tail()

,Dyad,Session,Time_begin,P1,P2,SD,QE,SV,PR,HD,Match
1649,10,2,00:46:24.900000,nice snails,NaN,NaN,NaN,x,x,NaN,"[('nice snails', 100), [10, 2, '00:46:24.938']]"
1650,10,2,00:46:26.600000,NaN,thanks I only did one hand,NaN,NaN,x,NaN,NaN,"[('thanks I only did one hand', 100), [10, 2, ..."
1651,10,2,00:46:28.400000,nice,NaN,NaN,NaN,x,x,NaN,"[('nice', 100), [10, 2, '00:46:28.378']]"
1652,10,2,00:46:29.200000,NaN,I was too lazy okay,NaN,NaN,x,NaN,NaN,"[('I was too lazy okay', 100), [10, 2, '00:46:..."
1653,10,2,00:46:30.900000,yeah that's me,NaN,NaN,NaN,x,NaN,NaN,"[(""yeah that's me"", 100), [10, 2, '00:46:30.84..."

In [6]:
def func(x):
    try :
        x=eval(x)
        res = pd.Series([
            x[0][0], x[0][1] , x[1][0], x[1][1], x[1][2]
            ])
        return res
    except : return x

df[['match', 'score', 'dyad', 'session', 'time_begin']] = df.Match.apply(func)
df.drop(columns=['Match'], inplace=True)
df.head()

,Dyad,Session,Time_begin,P1,P2,SD,QE,SV,PR,HD,match,score,dyad,session,time_begin
9322,3,1,00:00:43.600000,this is weird I think,NaN,x,NaN,NaN,NaN,NaN,this is weird I,95,3,1,00:00:45.135
9324,3,1,00:00:48.600000,NaN,maybe if you just hit undo button or something,NaN,NaN,NaN,NaN,x,maybe if you just hit undo button or something,100,3,1,00:00:51.000
9347,3,1,00:02:17.000000,NaN,I just can't see the problem,NaN,NaN,NaN,NaN,x,I see green on most of the pages I just can't ...,90,3,1,00:02:15.080
9349,3,1,00:02:30.600000,I don't know if you saw that,NaN,x,NaN,NaN,NaN,NaN,I don't know if you saw that,100,3,1,00:02:30.730
9364,3,1,00:03:16.300000,okay so pause filler so what's your name,NaN,NaN,x,NaN,NaN,NaN,okay so pause filler so what's your name,95,3,1,00:03:16.336

In [46]:
df_int = df[['dyad', 'session', 'time_begin','match', 'score', 'SD', 'QE', 'SV', 'PR', 'HD']].values
df_int = pd.DataFrame(df_int, columns=['dyad', 'session', 'time_begin','match', 'score', 'SD', 'QE', 'SV', 'PR', 'HD'])
df_int['id'] = df_int.dyad.astype(str) + ' - ' + df_int.session.astype(str) + ' - ' + pd.to_datetime(df_int.time_begin, format='%H:%M:%S.%f').dt.strftime("%H:%M:%S.%f").str.split('.', expand=True)[0]
df_int['idd'] = df_int.match.astype(str) + ' - ' + pd.to_datetime(df_int.time_begin, format='%H:%M:%S.%f').dt.strftime("%H:%M:%S.%f").str.split('.', expand=True)[0]
df_int.head()

,dyad,session,time_begin,match,score,SD,QE,SV,PR,HD,id,idd
0,3,1,00:00:45.135,this is weird I,95,x,NaN,NaN,NaN,NaN,3 - 1 - 00:00:45,this is weird I - 00:00:45
1,3,1,00:00:51.000,maybe if you just hit undo button or something,100,NaN,NaN,NaN,NaN,x,3 - 1 - 00:00:51,maybe if you just hit undo button or something...
2,3,1,00:02:15.080,I see green on most of the pages I just can't ...,90,NaN,NaN,NaN,NaN,x,3 - 1 - 00:02:15,I see green on most of the pages I just can't ...
3,3,1,00:02:30.730,I don't know if you saw that,100,x,NaN,NaN,NaN,NaN,3 - 1 - 00:02:30,I don't know if you saw that - 00:02:30
4,3,1,00:03:16.336,okay so pause filler so what's your name,95,NaN,x,NaN,NaN,NaN,3 - 1 - 00:03:16,okay so pause filler so what's your name - 00:...

In [51]:
full = pd.read_csv("data/transcripts/whole_data_2021_2016.csv", index_col=[0])
full['id'] = full.Dyad.astype(str) + ' - ' + full.Session.astype(str) + ' - ' + pd.to_datetime(full.Time_begin, format='%M:%S.%f').dt.strftime("%H:%M:%S.%f").str.split('.', expand=True)[0]
full['id1'] = full.P1.astype(str)+ ' - ' + pd.to_datetime(full.Time_begin, format='%M:%S.%f').dt.strftime("%H:%M:%S.%f").str.split('.', expand=True)[0]
full['id2'] = full.P2.astype(str)+ ' - ' + pd.to_datetime(full.Time_begin, format='%M:%S.%f').dt.strftime("%H:%M:%S.%f").str.split('.', expand=True)[0]
full.head()

,Dyad,Session,Period,P1,P2,Time_begin,Time_end,Duration,SV_Tutor,SV_Tutee,PR_Tutor,PR_Tutee,SD_Tutor,SD_Tutee,id,id1,id2
9306,3,1,S1,NaN,NaN,00:01.0,05:13.0,05:12.0,NaN,NaN,NaN,NaN,NaN,NaN,3 - 1 - 00:00:01,nan - 00:00:01,nan - 00:00:01
9307,3,1,S1,NaN,yeah I can hear you now (laughter),00:03.0,00:06.0,00:03.0,NaN,NaN,NaN,NaN,NaN,NaN,3 - 1 - 00:00:03,nan - 00:00:03,yeah I can hear you now (laughter) - 00:00:03
9308,3,1,S1,pause filler that's good pause filler,NaN,00:07.0,00:09.0,00:02.0,NaN,NaN,NaN,NaN,NaN,NaN,3 - 1 - 00:00:07,pause filler that's good pause filler - 00:00:07,nan - 00:00:07
9309,3,1,S1,oh loading,NaN,00:09.0,00:09.0,00:00.0,NaN,NaN,NaN,NaN,NaN,NaN,3 - 1 - 00:00:09,oh loading - 00:00:09,nan - 00:00:09
9310,3,1,S1,did I hit something,NaN,00:10.0,00:11.0,00:01.0,NaN,NaN,NaN,NaN,NaN,NaN,3 - 1 - 00:00:10,did I hit something - 00:00:10,nan - 00:00:10

In [57]:
len(set(full.id1).intersection(set(df_int.idd)).union(set(full.id2).intersection(set(df_int.idd))))

223

In [56]:
len(set(df_int.idd))

2083

In [62]:
len(set(df_int.id))

2038

In [64]:
len(set(df_int.id).intersection(set(full.id)))

536